### ISSUE TITLE
Lab manual screenshots not available in Company database.txt

### ISSUE THREAD

**Issue by Devansh-kajve** [JustA3DObject/SQL-basics#3]
Add the screenshots for good karma

**Comment by JustA3DObject** [comment]
Coming soon in the dank SQL repo near you.

**Comment by JustA3DObject** [comment]
Here you go :)
[DBMS_LAB_MANUAL.pdf](https://github.com/JustA3DObject/SQL-basics/files/9767291/DBMS_LAB_MANUAL.pdf)
